(cl:in-package realsense_ros_person-msg)
(cl:export '(ISRECOGNITIONENABLED-VAL
          ISRECOGNITIONENABLED
          ISSKELETONENABLED-VAL
          ISSKELETONENABLED
          ISGESTURESENABLED-VAL
          ISGESTURESENABLED
          ISLANDMARKSENABLED-VAL
          ISLANDMARKSENABLED
          ISHEADBOUNDINGBOXENABLED-VAL
          ISHEADBOUNDINGBOXENABLED
          ISHEADPOSEENABLED-VAL
          ISHEADPOSEENABLED
          ISTRACKINGENABLED-VAL
          ISTRACKINGENABLED
          TRACKINGSTATE-VAL
          TRACKINGSTATE
))