(cl:in-package realsense_ros_person-srv)
(cl:export '(ENABLERECOGNITION-VAL
          ENABLERECOGNITION
          ENABLESKELETON-VAL
          ENABLESKELETON
          ENABLEPOINTINGGESTURE-VAL
          ENABLEPOINTINGGESTURE
          ENABLEWAVEGESTURE-VAL
          ENABLEWAVEGESTURE
          ENABLELANDMARKS-VAL
          ENABLELANDMARKS
          ENABLEHEADBOUNDINGBOX-VAL
          ENABLEHEADBOUNDINGBOX
          ENABLEHEADPOSE-VAL
          ENABLEHEADPOSE
          STATUS-VAL
          STATUS
))