// Generated by gencpp from file object_msgs/DetectObjectRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_DETECTOBJECTREQUEST_H
#define OBJECT_MSGS_MESSAGE_DETECTOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_msgs
{
template <class ContainerAllocator>
struct DetectObjectRequest_
{
  typedef DetectObjectRequest_<ContainerAllocator> Type;

  DetectObjectRequest_()
    : image_paths()  {
    }
  DetectObjectRequest_(const ContainerAllocator& _alloc)
    : image_paths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _image_paths_type;
  _image_paths_type image_paths;





  typedef boost::shared_ptr< ::object_msgs::DetectObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::DetectObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectRequest_

typedef ::object_msgs::DetectObjectRequest_<std::allocator<void> > DetectObjectRequest;

typedef boost::shared_ptr< ::object_msgs::DetectObjectRequest > DetectObjectRequestPtr;
typedef boost::shared_ptr< ::object_msgs::DetectObjectRequest const> DetectObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::DetectObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_msgs': ['/home/complubot/Documents/POLLOTRON/CODE/ros/pollotron/src/object_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::DetectObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::DetectObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::DetectObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "072900a9ae5534db8c876cf096c6bdb1";
  }

  static const char* value(const ::object_msgs::DetectObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x072900a9ae5534dbULL;
  static const uint64_t static_value2 = 0x8c876cf096c6bdb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/DetectObjectRequest";
  }

  static const char* value(const ::object_msgs::DetectObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
string[] image_paths\n\
";
  }

  static const char* value(const ::object_msgs::DetectObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::DetectObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::DetectObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_paths[]" << std::endl;
    for (size_t i = 0; i < v.image_paths.size(); ++i)
    {
      s << indent << "  image_paths[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_DETECTOBJECTREQUEST_H
