// Generated by gencpp from file az5/simple_odom.msg
// DO NOT EDIT!


#ifndef AZ5_MESSAGE_SIMPLE_ODOM_H
#define AZ5_MESSAGE_SIMPLE_ODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace az5
{
template <class ContainerAllocator>
struct simple_odom_
{
  typedef simple_odom_<ContainerAllocator> Type;

  simple_odom_()
    : x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)
    , x_vel(0.0)
    , y_vel(0.0)
    , z_vel(0.0)  {
    }
  simple_odom_(const ContainerAllocator& _alloc)
    : x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)
    , x_vel(0.0)
    , y_vel(0.0)
    , z_vel(0.0)  {
  (void)_alloc;
    }



   typedef double _x_pos_type;
  _x_pos_type x_pos;

   typedef double _y_pos_type;
  _y_pos_type y_pos;

   typedef double _z_pos_type;
  _z_pos_type z_pos;

   typedef double _x_vel_type;
  _x_vel_type x_vel;

   typedef double _y_vel_type;
  _y_vel_type y_vel;

   typedef double _z_vel_type;
  _z_vel_type z_vel;





  typedef boost::shared_ptr< ::az5::simple_odom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::az5::simple_odom_<ContainerAllocator> const> ConstPtr;

}; // struct simple_odom_

typedef ::az5::simple_odom_<std::allocator<void> > simple_odom;

typedef boost::shared_ptr< ::az5::simple_odom > simple_odomPtr;
typedef boost::shared_ptr< ::az5::simple_odom const> simple_odomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::az5::simple_odom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::az5::simple_odom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace az5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'az5': ['/home/complubot/Documents/POLLOTRON/CODE/ros/pollotron/src/az5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::az5::simple_odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::az5::simple_odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::az5::simple_odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::az5::simple_odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::az5::simple_odom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::az5::simple_odom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::az5::simple_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22ab75215cf03e4c6396d04a16d3439c";
  }

  static const char* value(const ::az5::simple_odom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22ab75215cf03e4cULL;
  static const uint64_t static_value2 = 0x6396d04a16d3439cULL;
};

template<class ContainerAllocator>
struct DataType< ::az5::simple_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "az5/simple_odom";
  }

  static const char* value(const ::az5::simple_odom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::az5::simple_odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float64 x_pos\n\
float64 y_pos\n\
float64 z_pos\n\
float64 x_vel\n\
float64 y_vel\n\
float64 z_vel\n\
";
  }

  static const char* value(const ::az5::simple_odom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::az5::simple_odom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.z_pos);
      stream.next(m.x_vel);
      stream.next(m.y_vel);
      stream.next(m.z_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_odom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::az5::simple_odom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::az5::simple_odom_<ContainerAllocator>& v)
  {
    s << indent << "x_pos: ";
    Printer<double>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<double>::stream(s, indent + "  ", v.y_pos);
    s << indent << "z_pos: ";
    Printer<double>::stream(s, indent + "  ", v.z_pos);
    s << indent << "x_vel: ";
    Printer<double>::stream(s, indent + "  ", v.x_vel);
    s << indent << "y_vel: ";
    Printer<double>::stream(s, indent + "  ", v.y_vel);
    s << indent << "z_vel: ";
    Printer<double>::stream(s, indent + "  ", v.z_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AZ5_MESSAGE_SIMPLE_ODOM_H
