// Generated by gencpp from file az5/ultrasounds.msg
// DO NOT EDIT!


#ifndef AZ5_MESSAGE_ULTRASOUNDS_H
#define AZ5_MESSAGE_ULTRASOUNDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace az5
{
template <class ContainerAllocator>
struct ultrasounds_
{
  typedef ultrasounds_<ContainerAllocator> Type;

  ultrasounds_()
    : us(0)
    , value(0)  {
    }
  ultrasounds_(const ContainerAllocator& _alloc)
    : us(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int32_t _us_type;
  _us_type us;

   typedef int32_t _value_type;
  _value_type value;



  enum {
    length = 16,
  };


  typedef boost::shared_ptr< ::az5::ultrasounds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::az5::ultrasounds_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasounds_

typedef ::az5::ultrasounds_<std::allocator<void> > ultrasounds;

typedef boost::shared_ptr< ::az5::ultrasounds > ultrasoundsPtr;
typedef boost::shared_ptr< ::az5::ultrasounds const> ultrasoundsConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::az5::ultrasounds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::az5::ultrasounds_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace az5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'az5': ['/home/complubot/Documents/POLLOTRON/CODE/ros/pollotron/src/az5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::az5::ultrasounds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::az5::ultrasounds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::az5::ultrasounds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::az5::ultrasounds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::az5::ultrasounds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::az5::ultrasounds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::az5::ultrasounds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e30bc51109991e924faa9021922381b";
  }

  static const char* value(const ::az5::ultrasounds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e30bc51109991e9ULL;
  static const uint64_t static_value2 = 0x24faa9021922381bULL;
};

template<class ContainerAllocator>
struct DataType< ::az5::ultrasounds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "az5/ultrasounds";
  }

  static const char* value(const ::az5::ultrasounds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::az5::ultrasounds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 us\n\
int32 value\n\
int32 length = 16\n\
";
  }

  static const char* value(const ::az5::ultrasounds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::az5::ultrasounds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.us);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasounds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::az5::ultrasounds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::az5::ultrasounds_<ContainerAllocator>& v)
  {
    s << indent << "us: ";
    Printer<int32_t>::stream(s, indent + "  ", v.us);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AZ5_MESSAGE_ULTRASOUNDS_H
