#!/usr/bin/env python3
import sys
from os.path import dirname
sys.path.append(dirname('/home/complubot/Documents/POLLOTRON/CODE/ros/pollotron/src/az5/src/joystick_reader'))
from joystick_reader import main
    
if __name__ == '__main__':
    main.main()