// Generated by gencpp from file realsense_ros_person/EulerAnglesWithConfidence.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_EULERANGLESWITHCONFIDENCE_H
#define REALSENSE_ROS_PERSON_MESSAGE_EULERANGLESWITHCONFIDENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <realsense_ros_person/EulerAngles.h>

namespace realsense_ros_person
{
template <class ContainerAllocator>
struct EulerAnglesWithConfidence_
{
  typedef EulerAnglesWithConfidence_<ContainerAllocator> Type;

  EulerAnglesWithConfidence_()
    : angles()
    , confidence(0)  {
    }
  EulerAnglesWithConfidence_(const ContainerAllocator& _alloc)
    : angles(_alloc)
    , confidence(0)  {
  (void)_alloc;
    }



   typedef  ::realsense_ros_person::EulerAngles_<ContainerAllocator>  _angles_type;
  _angles_type angles;

   typedef int32_t _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> const> ConstPtr;

}; // struct EulerAnglesWithConfidence_

typedef ::realsense_ros_person::EulerAnglesWithConfidence_<std::allocator<void> > EulerAnglesWithConfidence;

typedef boost::shared_ptr< ::realsense_ros_person::EulerAnglesWithConfidence > EulerAnglesWithConfidencePtr;
typedef boost::shared_ptr< ::realsense_ros_person::EulerAnglesWithConfidence const> EulerAnglesWithConfidenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e76354a4d10460adcef4d7d5dd74f1f";
  }

  static const char* value(const ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e76354a4d10460aULL;
  static const uint64_t static_value2 = 0xdcef4d7d5dd74f1fULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/EulerAnglesWithConfidence";
  }

  static const char* value(const ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EulerAngles angles\n\
int32 confidence\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/EulerAngles\n\
float32 pitch\n\
float32 roll\n\
float32 yaw\n\
";
  }

  static const char* value(const ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerAnglesWithConfidence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::EulerAnglesWithConfidence_<ContainerAllocator>& v)
  {
    s << indent << "angles: ";
    s << std::endl;
    Printer< ::realsense_ros_person::EulerAngles_<ContainerAllocator> >::stream(s, indent + "  ", v.angles);
    s << indent << "confidence: ";
    Printer<int32_t>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_EULERANGLESWITHCONFIDENCE_H
