// Generated by gencpp from file realsense_ros_person/Frame.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_FRAME_H
#define REALSENSE_ROS_PERSON_MESSAGE_FRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <realsense_ros_person/User.h>

namespace realsense_ros_person
{
template <class ContainerAllocator>
struct Frame_
{
  typedef Frame_<ContainerAllocator> Type;

  Frame_()
    : numberOfUsers(0)
    , usersData()  {
    }
  Frame_(const ContainerAllocator& _alloc)
    : numberOfUsers(0)
    , usersData(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _numberOfUsers_type;
  _numberOfUsers_type numberOfUsers;

   typedef std::vector< ::realsense_ros_person::User_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::realsense_ros_person::User_<ContainerAllocator> >::other >  _usersData_type;
  _usersData_type usersData;





  typedef boost::shared_ptr< ::realsense_ros_person::Frame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::Frame_<ContainerAllocator> const> ConstPtr;

}; // struct Frame_

typedef ::realsense_ros_person::Frame_<std::allocator<void> > Frame;

typedef boost::shared_ptr< ::realsense_ros_person::Frame > FramePtr;
typedef boost::shared_ptr< ::realsense_ros_person::Frame const> FrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::Frame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::Frame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::Frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::Frame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::Frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::Frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::Frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::Frame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fc1584508d060a88fda97d4fdfd469b";
  }

  static const char* value(const ::realsense_ros_person::Frame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fc1584508d060a8ULL;
  static const uint64_t static_value2 = 0x8fda97d4fdfd469bULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/Frame";
  }

  static const char* value(const ::realsense_ros_person::Frame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::Frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 numberOfUsers\n\
User[] usersData\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/User\n\
UserInfo userInfo\n\
geometry_msgs/Point32 centerOfMassImage\n\
geometry_msgs/Point32 centerOfMassWorld\n\
RectWithConfidence userRect\n\
RectWithConfidence headBoundingBox\n\
LandmarksInfo landmarksInfo\n\
EulerAnglesWithConfidence headPose\n\
SkeletonJoint[] skeletonJoints\n\
Gestures gestures\n\
\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/UserInfo\n\
int32 Id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: realsense_ros_person/RectWithConfidence\n\
int32 confidence\n\
geometry_msgs/Point32[2] rectCorners\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/LandmarksInfo\n\
int32 confidence\n\
Landmark[] landmarks\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/Landmark\n\
geometry_msgs/Point location\n\
geometry_msgs/Point32 realWorldCoordinates\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/EulerAnglesWithConfidence\n\
EulerAngles angles\n\
int32 confidence\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/EulerAngles\n\
float32 pitch\n\
float32 roll\n\
float32 yaw\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/SkeletonJoint\n\
int32 type\n\
float32 confidence\n\
geometry_msgs/Point location\n\
geometry_msgs/Point32 realWorldCoordinates\n\
\n\
#joint types constants\n\
int32 JOINT_ANKLE_LEFT=0\n\
int32 JOINT_ANKLE_RIGHT=1\n\
int32 JOINT_ELBOW_LEFT=2\n\
int32 JOINT_ELBOW_RIGHT=3\n\
int32 JOINT_FOOT_LEFT=4\n\
int32 JOINT_FOOT_RIGHT=5\n\
int32 JOINT_HAND_LEFT=6\n\
int32 JOINT_HAND_RIGHT=7\n\
int32 JOINT_HAND_TIP_LEFT=8\n\
int32 JOINT_HAND_TIP_RIGHT=9\n\
int32 JOINT_HEAD=10\n\
int32 JOINT_HIP_LEFT=11\n\
int32 JOINT_HIP_RIGHT=12\n\
int32 JOINT_KNEE_LEFT=13\n\
int32 JOINT_KNEE_RIGHT=14\n\
int32 JOINT_NECK=15\n\
int32 JOINT_SHOULDER_LEFT=16\n\
int32 JOINT_SHOULDER_RIGHT=17\n\
int32 JOINT_SPINE_BASE=18\n\
int32 JOINT_SPINE_MID=19\n\
int32 JOINT_SPINE_SHOULDER=20\n\
int32 JOINT_THUMB_LEFT=21\n\
int32 JOINT_THUMB_RIGHT=22\n\
int32 JOINT_WRIST_LEFT=23\n\
int32 JOINT_WRIST_RIGHT=24\n\
int32 JOINT_UNKNOWN=25\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/Gestures\n\
Pointing pointing\n\
Wave wave\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/Pointing\n\
int32 confidence\n\
geometry_msgs/Point32 originColor\n\
geometry_msgs/Point32 originWorld\n\
geometry_msgs/Point32 orientationColor\n\
geometry_msgs/Vector3 orientationWorld\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: realsense_ros_person/Wave\n\
int32 type\n\
\n\
#Wave gesture types\n\
int32 WAVE_NOT_DETECTED=-1 # Wave not detected \n\
int32 WAVE_LEFT_LA=1       # Wave ended with hand motion to the left, in the left area\n\
int32 WAVE_RIGHT_LA=2      # Wave ended with hand motion to the right, in the left area\n\
int32 WAVE_LEFT_RA=3       # Wave ended with hand motion to the left, in the right area\n\
int32 WAVE_RIGHT_RA=4      # Wave ended with hand motion to the right, in the right area\n\
\n\
";
  }

  static const char* value(const ::realsense_ros_person::Frame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::Frame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numberOfUsers);
      stream.next(m.usersData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Frame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::Frame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::Frame_<ContainerAllocator>& v)
  {
    s << indent << "numberOfUsers: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numberOfUsers);
    s << indent << "usersData[]" << std::endl;
    for (size_t i = 0; i < v.usersData.size(); ++i)
    {
      s << indent << "  usersData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::realsense_ros_person::User_<ContainerAllocator> >::stream(s, indent + "    ", v.usersData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_FRAME_H
