// Generated by gencpp from file realsense_ros_person/Gestures.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_GESTURES_H
#define REALSENSE_ROS_PERSON_MESSAGE_GESTURES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <realsense_ros_person/Pointing.h>
#include <realsense_ros_person/Wave.h>

namespace realsense_ros_person
{
template <class ContainerAllocator>
struct Gestures_
{
  typedef Gestures_<ContainerAllocator> Type;

  Gestures_()
    : pointing()
    , wave()  {
    }
  Gestures_(const ContainerAllocator& _alloc)
    : pointing(_alloc)
    , wave(_alloc)  {
  (void)_alloc;
    }



   typedef  ::realsense_ros_person::Pointing_<ContainerAllocator>  _pointing_type;
  _pointing_type pointing;

   typedef  ::realsense_ros_person::Wave_<ContainerAllocator>  _wave_type;
  _wave_type wave;





  typedef boost::shared_ptr< ::realsense_ros_person::Gestures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::Gestures_<ContainerAllocator> const> ConstPtr;

}; // struct Gestures_

typedef ::realsense_ros_person::Gestures_<std::allocator<void> > Gestures;

typedef boost::shared_ptr< ::realsense_ros_person::Gestures > GesturesPtr;
typedef boost::shared_ptr< ::realsense_ros_person::Gestures const> GesturesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::Gestures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::Gestures_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::Gestures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::Gestures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::Gestures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::Gestures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::Gestures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::Gestures_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::Gestures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3676ee03e8d847bc8d129f9b683163e";
  }

  static const char* value(const ::realsense_ros_person::Gestures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3676ee03e8d847bULL;
  static const uint64_t static_value2 = 0xc8d129f9b683163eULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::Gestures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/Gestures";
  }

  static const char* value(const ::realsense_ros_person::Gestures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::Gestures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pointing pointing\n\
Wave wave\n\
\n\
================================================================================\n\
MSG: realsense_ros_person/Pointing\n\
int32 confidence\n\
geometry_msgs/Point32 originColor\n\
geometry_msgs/Point32 originWorld\n\
geometry_msgs/Point32 orientationColor\n\
geometry_msgs/Vector3 orientationWorld\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: realsense_ros_person/Wave\n\
int32 type\n\
\n\
#Wave gesture types\n\
int32 WAVE_NOT_DETECTED=-1 # Wave not detected \n\
int32 WAVE_LEFT_LA=1       # Wave ended with hand motion to the left, in the left area\n\
int32 WAVE_RIGHT_LA=2      # Wave ended with hand motion to the right, in the left area\n\
int32 WAVE_LEFT_RA=3       # Wave ended with hand motion to the left, in the right area\n\
int32 WAVE_RIGHT_RA=4      # Wave ended with hand motion to the right, in the right area\n\
\n\
";
  }

  static const char* value(const ::realsense_ros_person::Gestures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::Gestures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointing);
      stream.next(m.wave);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gestures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::Gestures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::Gestures_<ContainerAllocator>& v)
  {
    s << indent << "pointing: ";
    s << std::endl;
    Printer< ::realsense_ros_person::Pointing_<ContainerAllocator> >::stream(s, indent + "  ", v.pointing);
    s << indent << "wave: ";
    s << std::endl;
    Printer< ::realsense_ros_person::Wave_<ContainerAllocator> >::stream(s, indent + "  ", v.wave);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_GESTURES_H
