// Generated by gencpp from file realsense_ros_person/LoadRecognitionDB.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_LOADRECOGNITIONDB_H
#define REALSENSE_ROS_PERSON_MESSAGE_LOADRECOGNITIONDB_H

#include <ros/service_traits.h>


#include <realsense_ros_person/LoadRecognitionDBRequest.h>
#include <realsense_ros_person/LoadRecognitionDBResponse.h>


namespace realsense_ros_person
{

struct LoadRecognitionDB
{

typedef LoadRecognitionDBRequest Request;
typedef LoadRecognitionDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadRecognitionDB
} // namespace realsense_ros_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_person::LoadRecognitionDB > {
  static const char* value()
  {
    return "1831e0f589127bcbfbf3f10b978cf7a3";
  }

  static const char* value(const ::realsense_ros_person::LoadRecognitionDB&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_person::LoadRecognitionDB > {
  static const char* value()
  {
    return "realsense_ros_person/LoadRecognitionDB";
  }

  static const char* value(const ::realsense_ros_person::LoadRecognitionDB&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_person::LoadRecognitionDBRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_person::LoadRecognitionDB > 
template<>
struct MD5Sum< ::realsense_ros_person::LoadRecognitionDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::LoadRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::LoadRecognitionDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::LoadRecognitionDBRequest> should match 
// service_traits::DataType< ::realsense_ros_person::LoadRecognitionDB > 
template<>
struct DataType< ::realsense_ros_person::LoadRecognitionDBRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::LoadRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::LoadRecognitionDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_person::LoadRecognitionDBResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_person::LoadRecognitionDB > 
template<>
struct MD5Sum< ::realsense_ros_person::LoadRecognitionDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::LoadRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::LoadRecognitionDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::LoadRecognitionDBResponse> should match 
// service_traits::DataType< ::realsense_ros_person::LoadRecognitionDB > 
template<>
struct DataType< ::realsense_ros_person::LoadRecognitionDBResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::LoadRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::LoadRecognitionDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_LOADRECOGNITIONDB_H
