// Generated by gencpp from file realsense_ros_person/RecognitionResponse.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_RECOGNITIONRESPONSE_H
#define REALSENSE_ROS_PERSON_MESSAGE_RECOGNITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ros_person
{
template <class ContainerAllocator>
struct RecognitionResponse_
{
  typedef RecognitionResponse_<ContainerAllocator> Type;

  RecognitionResponse_()
    : status(0)
    , recognitionId(0)
    , similarityScore(0.0)  {
    }
  RecognitionResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , recognitionId(0)
    , similarityScore(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef int32_t _recognitionId_type;
  _recognitionId_type recognitionId;

   typedef float _similarityScore_type;
  _similarityScore_type similarityScore;



  enum {
    RECOGNITION_PASSED_PERSON_RECOGNIZED = 0,
    RECOGNITION_PASSED_PERSON_NOT_RECOGNIZED = 1,
    RECOGNITION_FAILED = 2,
    RECOGNITION_FAILED_FACE_NOT_DETECTED = 3,
    RECOGNITION_FAILED_FACE_NOT_CLEAR = 4,
    RECOGNITION_FAILED_PERSON_TOO_FAR = 5,
    RECOGNITION_FAILED_PERSON_TOO_CLOSE = 6,
    RECOGNITION_FAILED_FACE_AMBIGUITY = 7,
  };


  typedef boost::shared_ptr< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognitionResponse_

typedef ::realsense_ros_person::RecognitionResponse_<std::allocator<void> > RecognitionResponse;

typedef boost::shared_ptr< ::realsense_ros_person::RecognitionResponse > RecognitionResponsePtr;
typedef boost::shared_ptr< ::realsense_ros_person::RecognitionResponse const> RecognitionResponseConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10f761f45f5fdb424410b79e3dc54b21";
  }

  static const char* value(const ::realsense_ros_person::RecognitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10f761f45f5fdb42ULL;
  static const uint64_t static_value2 = 0x4410b79e3dc54b21ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/RecognitionResponse";
  }

  static const char* value(const ::realsense_ros_person::RecognitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n\
int32 recognitionId\n\
float32 similarityScore\n\
\n\
\n\
int32 RECOGNITION_PASSED_PERSON_RECOGNIZED=0\n\
int32 RECOGNITION_PASSED_PERSON_NOT_RECOGNIZED=1\n\
int32 RECOGNITION_FAILED=2\n\
int32 RECOGNITION_FAILED_FACE_NOT_DETECTED=3\n\
int32 RECOGNITION_FAILED_FACE_NOT_CLEAR=4\n\
int32 RECOGNITION_FAILED_PERSON_TOO_FAR=5\n\
int32 RECOGNITION_FAILED_PERSON_TOO_CLOSE=6\n\
int32 RECOGNITION_FAILED_FACE_AMBIGUITY=7\n\
\n\
";
  }

  static const char* value(const ::realsense_ros_person::RecognitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.recognitionId);
      stream.next(m.similarityScore);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::RecognitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::RecognitionResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "recognitionId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.recognitionId);
    s << indent << "similarityScore: ";
    Printer<float>::stream(s, indent + "  ", v.similarityScore);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_RECOGNITIONRESPONSE_H
