// Generated by gencpp from file realsense_ros_person/SaveRecognitionDB.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_SAVERECOGNITIONDB_H
#define REALSENSE_ROS_PERSON_MESSAGE_SAVERECOGNITIONDB_H

#include <ros/service_traits.h>


#include <realsense_ros_person/SaveRecognitionDBRequest.h>
#include <realsense_ros_person/SaveRecognitionDBResponse.h>


namespace realsense_ros_person
{

struct SaveRecognitionDB
{

typedef SaveRecognitionDBRequest Request;
typedef SaveRecognitionDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveRecognitionDB
} // namespace realsense_ros_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_person::SaveRecognitionDB > {
  static const char* value()
  {
    return "1de971d723014a924e8ac6f15d9d1728";
  }

  static const char* value(const ::realsense_ros_person::SaveRecognitionDB&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_person::SaveRecognitionDB > {
  static const char* value()
  {
    return "realsense_ros_person/SaveRecognitionDB";
  }

  static const char* value(const ::realsense_ros_person::SaveRecognitionDB&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_person::SaveRecognitionDBRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_person::SaveRecognitionDB > 
template<>
struct MD5Sum< ::realsense_ros_person::SaveRecognitionDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::SaveRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::SaveRecognitionDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::SaveRecognitionDBRequest> should match 
// service_traits::DataType< ::realsense_ros_person::SaveRecognitionDB > 
template<>
struct DataType< ::realsense_ros_person::SaveRecognitionDBRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::SaveRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::SaveRecognitionDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_person::SaveRecognitionDBResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_person::SaveRecognitionDB > 
template<>
struct MD5Sum< ::realsense_ros_person::SaveRecognitionDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::SaveRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::SaveRecognitionDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::SaveRecognitionDBResponse> should match 
// service_traits::DataType< ::realsense_ros_person::SaveRecognitionDB > 
template<>
struct DataType< ::realsense_ros_person::SaveRecognitionDBResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::SaveRecognitionDB >::value();
  }
  static const char* value(const ::realsense_ros_person::SaveRecognitionDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_SAVERECOGNITIONDB_H
