// Generated by gencpp from file realsense_ros_person/SaveRecognitionDBRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_SAVERECOGNITIONDBREQUEST_H
#define REALSENSE_ROS_PERSON_MESSAGE_SAVERECOGNITIONDBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ros_person
{
template <class ContainerAllocator>
struct SaveRecognitionDBRequest_
{
  typedef SaveRecognitionDBRequest_<ContainerAllocator> Type;

  SaveRecognitionDBRequest_()
    : saveToPath()  {
    }
  SaveRecognitionDBRequest_(const ContainerAllocator& _alloc)
    : saveToPath(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _saveToPath_type;
  _saveToPath_type saveToPath;





  typedef boost::shared_ptr< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveRecognitionDBRequest_

typedef ::realsense_ros_person::SaveRecognitionDBRequest_<std::allocator<void> > SaveRecognitionDBRequest;

typedef boost::shared_ptr< ::realsense_ros_person::SaveRecognitionDBRequest > SaveRecognitionDBRequestPtr;
typedef boost::shared_ptr< ::realsense_ros_person::SaveRecognitionDBRequest const> SaveRecognitionDBRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6f54f323bfdd90f5dc74498f19562e3";
  }

  static const char* value(const ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6f54f323bfdd90fULL;
  static const uint64_t static_value2 = 0x5dc74498f19562e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/SaveRecognitionDBRequest";
  }

  static const char* value(const ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string saveToPath\n\
";
  }

  static const char* value(const ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.saveToPath);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveRecognitionDBRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::SaveRecognitionDBRequest_<ContainerAllocator>& v)
  {
    s << indent << "saveToPath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.saveToPath);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_SAVERECOGNITIONDBREQUEST_H
