// Generated by gencpp from file realsense_ros_person/SkeletonJoint.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_SKELETONJOINT_H
#define REALSENSE_ROS_PERSON_MESSAGE_SKELETONJOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point32.h>

namespace realsense_ros_person
{
template <class ContainerAllocator>
struct SkeletonJoint_
{
  typedef SkeletonJoint_<ContainerAllocator> Type;

  SkeletonJoint_()
    : type(0)
    , confidence(0.0)
    , location()
    , realWorldCoordinates()  {
    }
  SkeletonJoint_(const ContainerAllocator& _alloc)
    : type(0)
    , confidence(0.0)
    , location(_alloc)
    , realWorldCoordinates(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _location_type;
  _location_type location;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _realWorldCoordinates_type;
  _realWorldCoordinates_type realWorldCoordinates;



  enum {
    JOINT_ANKLE_LEFT = 0,
    JOINT_ANKLE_RIGHT = 1,
    JOINT_ELBOW_LEFT = 2,
    JOINT_ELBOW_RIGHT = 3,
    JOINT_FOOT_LEFT = 4,
    JOINT_FOOT_RIGHT = 5,
    JOINT_HAND_LEFT = 6,
    JOINT_HAND_RIGHT = 7,
    JOINT_HAND_TIP_LEFT = 8,
    JOINT_HAND_TIP_RIGHT = 9,
    JOINT_HEAD = 10,
    JOINT_HIP_LEFT = 11,
    JOINT_HIP_RIGHT = 12,
    JOINT_KNEE_LEFT = 13,
    JOINT_KNEE_RIGHT = 14,
    JOINT_NECK = 15,
    JOINT_SHOULDER_LEFT = 16,
    JOINT_SHOULDER_RIGHT = 17,
    JOINT_SPINE_BASE = 18,
    JOINT_SPINE_MID = 19,
    JOINT_SPINE_SHOULDER = 20,
    JOINT_THUMB_LEFT = 21,
    JOINT_THUMB_RIGHT = 22,
    JOINT_WRIST_LEFT = 23,
    JOINT_WRIST_RIGHT = 24,
    JOINT_UNKNOWN = 25,
  };


  typedef boost::shared_ptr< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> const> ConstPtr;

}; // struct SkeletonJoint_

typedef ::realsense_ros_person::SkeletonJoint_<std::allocator<void> > SkeletonJoint;

typedef boost::shared_ptr< ::realsense_ros_person::SkeletonJoint > SkeletonJointPtr;
typedef boost::shared_ptr< ::realsense_ros_person::SkeletonJoint const> SkeletonJointConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfca6d8f4a6c4e847fc126d5f1b7b05b";
  }

  static const char* value(const ::realsense_ros_person::SkeletonJoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfca6d8f4a6c4e84ULL;
  static const uint64_t static_value2 = 0x7fc126d5f1b7b05bULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/SkeletonJoint";
  }

  static const char* value(const ::realsense_ros_person::SkeletonJoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n\
float32 confidence\n\
geometry_msgs/Point location\n\
geometry_msgs/Point32 realWorldCoordinates\n\
\n\
#joint types constants\n\
int32 JOINT_ANKLE_LEFT=0\n\
int32 JOINT_ANKLE_RIGHT=1\n\
int32 JOINT_ELBOW_LEFT=2\n\
int32 JOINT_ELBOW_RIGHT=3\n\
int32 JOINT_FOOT_LEFT=4\n\
int32 JOINT_FOOT_RIGHT=5\n\
int32 JOINT_HAND_LEFT=6\n\
int32 JOINT_HAND_RIGHT=7\n\
int32 JOINT_HAND_TIP_LEFT=8\n\
int32 JOINT_HAND_TIP_RIGHT=9\n\
int32 JOINT_HEAD=10\n\
int32 JOINT_HIP_LEFT=11\n\
int32 JOINT_HIP_RIGHT=12\n\
int32 JOINT_KNEE_LEFT=13\n\
int32 JOINT_KNEE_RIGHT=14\n\
int32 JOINT_NECK=15\n\
int32 JOINT_SHOULDER_LEFT=16\n\
int32 JOINT_SHOULDER_RIGHT=17\n\
int32 JOINT_SPINE_BASE=18\n\
int32 JOINT_SPINE_MID=19\n\
int32 JOINT_SPINE_SHOULDER=20\n\
int32 JOINT_THUMB_LEFT=21\n\
int32 JOINT_THUMB_RIGHT=22\n\
int32 JOINT_WRIST_LEFT=23\n\
int32 JOINT_WRIST_RIGHT=24\n\
int32 JOINT_UNKNOWN=25\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::realsense_ros_person::SkeletonJoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.confidence);
      stream.next(m.location);
      stream.next(m.realWorldCoordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SkeletonJoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::SkeletonJoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::SkeletonJoint_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
    s << indent << "realWorldCoordinates: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.realWorldCoordinates);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_SKELETONJOINT_H
