// Generated by gencpp from file realsense_ros_person/StartTracking.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_STARTTRACKING_H
#define REALSENSE_ROS_PERSON_MESSAGE_STARTTRACKING_H

#include <ros/service_traits.h>


#include <realsense_ros_person/StartTrackingRequest.h>
#include <realsense_ros_person/StartTrackingResponse.h>


namespace realsense_ros_person
{

struct StartTracking
{

typedef StartTrackingRequest Request;
typedef StartTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartTracking
} // namespace realsense_ros_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_person::StartTracking > {
  static const char* value()
  {
    return "1b7f90a77bc2f8f3c4e3d407153b5435";
  }

  static const char* value(const ::realsense_ros_person::StartTracking&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_person::StartTracking > {
  static const char* value()
  {
    return "realsense_ros_person/StartTracking";
  }

  static const char* value(const ::realsense_ros_person::StartTracking&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_person::StartTrackingRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_person::StartTracking > 
template<>
struct MD5Sum< ::realsense_ros_person::StartTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::StartTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StartTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::StartTrackingRequest> should match 
// service_traits::DataType< ::realsense_ros_person::StartTracking > 
template<>
struct DataType< ::realsense_ros_person::StartTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::StartTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StartTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_person::StartTrackingResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_person::StartTracking > 
template<>
struct MD5Sum< ::realsense_ros_person::StartTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::StartTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StartTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::StartTrackingResponse> should match 
// service_traits::DataType< ::realsense_ros_person::StartTracking > 
template<>
struct DataType< ::realsense_ros_person::StartTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::StartTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StartTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_STARTTRACKING_H
