// Generated by gencpp from file realsense_ros_person/StartTrackingRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_STARTTRACKINGREQUEST_H
#define REALSENSE_ROS_PERSON_MESSAGE_STARTTRACKINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ros_person
{
template <class ContainerAllocator>
struct StartTrackingRequest_
{
  typedef StartTrackingRequest_<ContainerAllocator> Type;

  StartTrackingRequest_()
    : personId(0)  {
    }
  StartTrackingRequest_(const ContainerAllocator& _alloc)
    : personId(0)  {
  (void)_alloc;
    }



   typedef int32_t _personId_type;
  _personId_type personId;





  typedef boost::shared_ptr< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartTrackingRequest_

typedef ::realsense_ros_person::StartTrackingRequest_<std::allocator<void> > StartTrackingRequest;

typedef boost::shared_ptr< ::realsense_ros_person::StartTrackingRequest > StartTrackingRequestPtr;
typedef boost::shared_ptr< ::realsense_ros_person::StartTrackingRequest const> StartTrackingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d4730fa7bd1fbdf419fdc75b1b7e004";
  }

  static const char* value(const ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d4730fa7bd1fbdfULL;
  static const uint64_t static_value2 = 0x419fdc75b1b7e004ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/StartTrackingRequest";
  }

  static const char* value(const ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 personId\n\
";
  }

  static const char* value(const ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.personId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartTrackingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::StartTrackingRequest_<ContainerAllocator>& v)
  {
    s << indent << "personId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.personId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_STARTTRACKINGREQUEST_H
