// Generated by gencpp from file realsense_ros_person/StopTracking.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_STOPTRACKING_H
#define REALSENSE_ROS_PERSON_MESSAGE_STOPTRACKING_H

#include <ros/service_traits.h>


#include <realsense_ros_person/StopTrackingRequest.h>
#include <realsense_ros_person/StopTrackingResponse.h>


namespace realsense_ros_person
{

struct StopTracking
{

typedef StopTrackingRequest Request;
typedef StopTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopTracking
} // namespace realsense_ros_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_person::StopTracking > {
  static const char* value()
  {
    return "1b7f90a77bc2f8f3c4e3d407153b5435";
  }

  static const char* value(const ::realsense_ros_person::StopTracking&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_person::StopTracking > {
  static const char* value()
  {
    return "realsense_ros_person/StopTracking";
  }

  static const char* value(const ::realsense_ros_person::StopTracking&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_person::StopTrackingRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_person::StopTracking > 
template<>
struct MD5Sum< ::realsense_ros_person::StopTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StopTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::StopTrackingRequest> should match 
// service_traits::DataType< ::realsense_ros_person::StopTracking > 
template<>
struct DataType< ::realsense_ros_person::StopTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StopTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_person::StopTrackingResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_person::StopTracking > 
template<>
struct MD5Sum< ::realsense_ros_person::StopTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StopTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::StopTrackingResponse> should match 
// service_traits::DataType< ::realsense_ros_person::StopTracking > 
template<>
struct DataType< ::realsense_ros_person::StopTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::StopTracking >::value();
  }
  static const char* value(const ::realsense_ros_person::StopTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_STOPTRACKING_H
