// Generated by gencpp from file realsense_ros_person/TrackingConfig.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_TRACKINGCONFIG_H
#define REALSENSE_ROS_PERSON_MESSAGE_TRACKINGCONFIG_H

#include <ros/service_traits.h>


#include <realsense_ros_person/TrackingConfigRequest.h>
#include <realsense_ros_person/TrackingConfigResponse.h>


namespace realsense_ros_person
{

struct TrackingConfig
{

typedef TrackingConfigRequest Request;
typedef TrackingConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrackingConfig
} // namespace realsense_ros_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_person::TrackingConfig > {
  static const char* value()
  {
    return "78e03ba522060c37577ef42678654b8c";
  }

  static const char* value(const ::realsense_ros_person::TrackingConfig&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_person::TrackingConfig > {
  static const char* value()
  {
    return "realsense_ros_person/TrackingConfig";
  }

  static const char* value(const ::realsense_ros_person::TrackingConfig&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_person::TrackingConfigRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_person::TrackingConfig > 
template<>
struct MD5Sum< ::realsense_ros_person::TrackingConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::TrackingConfig >::value();
  }
  static const char* value(const ::realsense_ros_person::TrackingConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::TrackingConfigRequest> should match 
// service_traits::DataType< ::realsense_ros_person::TrackingConfig > 
template<>
struct DataType< ::realsense_ros_person::TrackingConfigRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::TrackingConfig >::value();
  }
  static const char* value(const ::realsense_ros_person::TrackingConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_person::TrackingConfigResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_person::TrackingConfig > 
template<>
struct MD5Sum< ::realsense_ros_person::TrackingConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_person::TrackingConfig >::value();
  }
  static const char* value(const ::realsense_ros_person::TrackingConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_person::TrackingConfigResponse> should match 
// service_traits::DataType< ::realsense_ros_person::TrackingConfig > 
template<>
struct DataType< ::realsense_ros_person::TrackingConfigResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_person::TrackingConfig >::value();
  }
  static const char* value(const ::realsense_ros_person::TrackingConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_TRACKINGCONFIG_H
