// Generated by gencpp from file realsense_ros_person/TrackingConfigRequest.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_TRACKINGCONFIGREQUEST_H
#define REALSENSE_ROS_PERSON_MESSAGE_TRACKINGCONFIGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ros_person
{
template <class ContainerAllocator>
struct TrackingConfigRequest_
{
  typedef TrackingConfigRequest_<ContainerAllocator> Type;

  TrackingConfigRequest_()
    : enableRecognition(false)
    , enableSkeleton(false)
    , enablePointingGesture(false)
    , enableWaveGesture(false)
    , enableLandmarks(false)
    , enableHeadBoundingBox(false)
    , enableHeadPose(false)  {
    }
  TrackingConfigRequest_(const ContainerAllocator& _alloc)
    : enableRecognition(false)
    , enableSkeleton(false)
    , enablePointingGesture(false)
    , enableWaveGesture(false)
    , enableLandmarks(false)
    , enableHeadBoundingBox(false)
    , enableHeadPose(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enableRecognition_type;
  _enableRecognition_type enableRecognition;

   typedef uint8_t _enableSkeleton_type;
  _enableSkeleton_type enableSkeleton;

   typedef uint8_t _enablePointingGesture_type;
  _enablePointingGesture_type enablePointingGesture;

   typedef uint8_t _enableWaveGesture_type;
  _enableWaveGesture_type enableWaveGesture;

   typedef uint8_t _enableLandmarks_type;
  _enableLandmarks_type enableLandmarks;

   typedef uint8_t _enableHeadBoundingBox_type;
  _enableHeadBoundingBox_type enableHeadBoundingBox;

   typedef uint8_t _enableHeadPose_type;
  _enableHeadPose_type enableHeadPose;





  typedef boost::shared_ptr< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TrackingConfigRequest_

typedef ::realsense_ros_person::TrackingConfigRequest_<std::allocator<void> > TrackingConfigRequest;

typedef boost::shared_ptr< ::realsense_ros_person::TrackingConfigRequest > TrackingConfigRequestPtr;
typedef boost::shared_ptr< ::realsense_ros_person::TrackingConfigRequest const> TrackingConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "686ca0728cbcd739a9efb35cc7c81a46";
  }

  static const char* value(const ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x686ca0728cbcd739ULL;
  static const uint64_t static_value2 = 0xa9efb35cc7c81a46ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/TrackingConfigRequest";
  }

  static const char* value(const ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enableRecognition\n\
bool enableSkeleton\n\
bool enablePointingGesture\n\
bool enableWaveGesture\n\
bool enableLandmarks\n\
bool enableHeadBoundingBox\n\
bool enableHeadPose\n\
";
  }

  static const char* value(const ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enableRecognition);
      stream.next(m.enableSkeleton);
      stream.next(m.enablePointingGesture);
      stream.next(m.enableWaveGesture);
      stream.next(m.enableLandmarks);
      stream.next(m.enableHeadBoundingBox);
      stream.next(m.enableHeadPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackingConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::TrackingConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "enableRecognition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableRecognition);
    s << indent << "enableSkeleton: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableSkeleton);
    s << indent << "enablePointingGesture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enablePointingGesture);
    s << indent << "enableWaveGesture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableWaveGesture);
    s << indent << "enableLandmarks: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableLandmarks);
    s << indent << "enableHeadBoundingBox: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableHeadBoundingBox);
    s << indent << "enableHeadPose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableHeadPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_TRACKINGCONFIGREQUEST_H
