// Generated by gencpp from file realsense_ros_person/Wave.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_PERSON_MESSAGE_WAVE_H
#define REALSENSE_ROS_PERSON_MESSAGE_WAVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ros_person
{
template <class ContainerAllocator>
struct Wave_
{
  typedef Wave_<ContainerAllocator> Type;

  Wave_()
    : type(0)  {
    }
  Wave_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef int32_t _type_type;
  _type_type type;



  enum {
    WAVE_NOT_DETECTED = -1,
    WAVE_LEFT_LA = 1,
    WAVE_RIGHT_LA = 2,
    WAVE_LEFT_RA = 3,
    WAVE_RIGHT_RA = 4,
  };


  typedef boost::shared_ptr< ::realsense_ros_person::Wave_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_person::Wave_<ContainerAllocator> const> ConstPtr;

}; // struct Wave_

typedef ::realsense_ros_person::Wave_<std::allocator<void> > Wave;

typedef boost::shared_ptr< ::realsense_ros_person::Wave > WavePtr;
typedef boost::shared_ptr< ::realsense_ros_person::Wave const> WaveConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_person::Wave_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_person::Wave_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_person

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'realsense_ros_person': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_person/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::Wave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_person::Wave_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::Wave_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_person::Wave_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::Wave_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_person::Wave_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_person::Wave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf1a205054ef9c51f0b3b2426adfe39a";
  }

  static const char* value(const ::realsense_ros_person::Wave_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf1a205054ef9c51ULL;
  static const uint64_t static_value2 = 0xf0b3b2426adfe39aULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_person::Wave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_person/Wave";
  }

  static const char* value(const ::realsense_ros_person::Wave_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_person::Wave_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 type\n\
\n\
#Wave gesture types\n\
int32 WAVE_NOT_DETECTED=-1 # Wave not detected \n\
int32 WAVE_LEFT_LA=1       # Wave ended with hand motion to the left, in the left area\n\
int32 WAVE_RIGHT_LA=2      # Wave ended with hand motion to the right, in the left area\n\
int32 WAVE_LEFT_RA=3       # Wave ended with hand motion to the left, in the right area\n\
int32 WAVE_RIGHT_RA=4      # Wave ended with hand motion to the right, in the right area\n\
\n\
";
  }

  static const char* value(const ::realsense_ros_person::Wave_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_person::Wave_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wave_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_person::Wave_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_person::Wave_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_PERSON_MESSAGE_WAVE_H
