// Generated by gencpp from file controller/bumpers.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_BUMPERS_H
#define CONTROLLER_MESSAGE_BUMPERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct bumpers_
{
  typedef bumpers_<ContainerAllocator> Type;

  bumpers_()
    : LEFT(false)
    , RIGHT(false)
    , FRONT(false)
    , BACK(false)  {
    }
  bumpers_(const ContainerAllocator& _alloc)
    : LEFT(false)
    , RIGHT(false)
    , FRONT(false)
    , BACK(false)  {
  (void)_alloc;
    }



   typedef uint8_t _LEFT_type;
  _LEFT_type LEFT;

   typedef uint8_t _RIGHT_type;
  _RIGHT_type RIGHT;

   typedef uint8_t _FRONT_type;
  _FRONT_type FRONT;

   typedef uint8_t _BACK_type;
  _BACK_type BACK;





  typedef boost::shared_ptr< ::controller::bumpers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::bumpers_<ContainerAllocator> const> ConstPtr;

}; // struct bumpers_

typedef ::controller::bumpers_<std::allocator<void> > bumpers;

typedef boost::shared_ptr< ::controller::bumpers > bumpersPtr;
typedef boost::shared_ptr< ::controller::bumpers const> bumpersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::bumpers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::bumpers_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'controller': ['/home/complubot/Documents/POLLOTRON/CODE/ros/controller/src/controller/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controller::bumpers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::bumpers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::bumpers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::bumpers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::bumpers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::bumpers_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::bumpers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b9e708bc1320c04ab698dfe0ba605f8";
  }

  static const char* value(const ::controller::bumpers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b9e708bc1320c04ULL;
  static const uint64_t static_value2 = 0xab698dfe0ba605f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::bumpers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/bumpers";
  }

  static const char* value(const ::controller::bumpers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::bumpers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool LEFT\n\
bool RIGHT\n\
bool FRONT\n\
bool BACK\n\
";
  }

  static const char* value(const ::controller::bumpers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::bumpers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LEFT);
      stream.next(m.RIGHT);
      stream.next(m.FRONT);
      stream.next(m.BACK);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bumpers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::bumpers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::bumpers_<ContainerAllocator>& v)
  {
    s << indent << "LEFT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LEFT);
    s << indent << "RIGHT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.RIGHT);
    s << indent << "FRONT: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FRONT);
    s << indent << "BACK: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BACK);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_BUMPERS_H
