// Generated by gencpp from file realsense_ros_slam/Reset.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_SLAM_MESSAGE_RESET_H
#define REALSENSE_ROS_SLAM_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <realsense_ros_slam/ResetRequest.h>
#include <realsense_ros_slam/ResetResponse.h>


namespace realsense_ros_slam
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace realsense_ros_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_slam::Reset > {
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::realsense_ros_slam::Reset&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_slam::Reset > {
  static const char* value()
  {
    return "realsense_ros_slam/Reset";
  }

  static const char* value(const ::realsense_ros_slam::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_slam::ResetRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_slam::Reset > 
template<>
struct MD5Sum< ::realsense_ros_slam::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_slam::Reset >::value();
  }
  static const char* value(const ::realsense_ros_slam::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_slam::ResetRequest> should match 
// service_traits::DataType< ::realsense_ros_slam::Reset > 
template<>
struct DataType< ::realsense_ros_slam::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_slam::Reset >::value();
  }
  static const char* value(const ::realsense_ros_slam::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_slam::ResetResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_slam::Reset > 
template<>
struct MD5Sum< ::realsense_ros_slam::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_slam::Reset >::value();
  }
  static const char* value(const ::realsense_ros_slam::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_slam::ResetResponse> should match 
// service_traits::DataType< ::realsense_ros_slam::Reset > 
template<>
struct DataType< ::realsense_ros_slam::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_slam::Reset >::value();
  }
  static const char* value(const ::realsense_ros_slam::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_SLAM_MESSAGE_RESET_H
