// Generated by gencpp from file realsense_ros_slam/SaveOutput.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_SLAM_MESSAGE_SAVEOUTPUT_H
#define REALSENSE_ROS_SLAM_MESSAGE_SAVEOUTPUT_H

#include <ros/service_traits.h>


#include <realsense_ros_slam/SaveOutputRequest.h>
#include <realsense_ros_slam/SaveOutputResponse.h>


namespace realsense_ros_slam
{

struct SaveOutput
{

typedef SaveOutputRequest Request;
typedef SaveOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveOutput
} // namespace realsense_ros_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_ros_slam::SaveOutput > {
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::realsense_ros_slam::SaveOutput&) { return value(); }
};

template<>
struct DataType< ::realsense_ros_slam::SaveOutput > {
  static const char* value()
  {
    return "realsense_ros_slam/SaveOutput";
  }

  static const char* value(const ::realsense_ros_slam::SaveOutput&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_ros_slam::SaveOutputRequest> should match 
// service_traits::MD5Sum< ::realsense_ros_slam::SaveOutput > 
template<>
struct MD5Sum< ::realsense_ros_slam::SaveOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_slam::SaveOutput >::value();
  }
  static const char* value(const ::realsense_ros_slam::SaveOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_slam::SaveOutputRequest> should match 
// service_traits::DataType< ::realsense_ros_slam::SaveOutput > 
template<>
struct DataType< ::realsense_ros_slam::SaveOutputRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_slam::SaveOutput >::value();
  }
  static const char* value(const ::realsense_ros_slam::SaveOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_ros_slam::SaveOutputResponse> should match 
// service_traits::MD5Sum< ::realsense_ros_slam::SaveOutput > 
template<>
struct MD5Sum< ::realsense_ros_slam::SaveOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_ros_slam::SaveOutput >::value();
  }
  static const char* value(const ::realsense_ros_slam::SaveOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_ros_slam::SaveOutputResponse> should match 
// service_traits::DataType< ::realsense_ros_slam::SaveOutput > 
template<>
struct DataType< ::realsense_ros_slam::SaveOutputResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_ros_slam::SaveOutput >::value();
  }
  static const char* value(const ::realsense_ros_slam::SaveOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_ROS_SLAM_MESSAGE_SAVEOUTPUT_H
