// Generated by gencpp from file realsense_ros_slam/TrackingAccuracy.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_SLAM_MESSAGE_TRACKINGACCURACY_H
#define REALSENSE_ROS_SLAM_MESSAGE_TRACKINGACCURACY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace realsense_ros_slam
{
template <class ContainerAllocator>
struct TrackingAccuracy_
{
  typedef TrackingAccuracy_<ContainerAllocator> Type;

  TrackingAccuracy_()
    : header()
    , tracking_accuracy(0)  {
    }
  TrackingAccuracy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracking_accuracy(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _tracking_accuracy_type;
  _tracking_accuracy_type tracking_accuracy;



  enum {
    TRACKING_ACCURACY_FAILED = 0,
    TRACKING_ACCURACY_LOW = 1,
    TRACKING_ACCURACY_MEDIUM = 2,
    TRACKING_ACCURACY_HIGH = 3,
  };


  typedef boost::shared_ptr< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> const> ConstPtr;

}; // struct TrackingAccuracy_

typedef ::realsense_ros_slam::TrackingAccuracy_<std::allocator<void> > TrackingAccuracy;

typedef boost::shared_ptr< ::realsense_ros_slam::TrackingAccuracy > TrackingAccuracyPtr;
typedef boost::shared_ptr< ::realsense_ros_slam::TrackingAccuracy const> TrackingAccuracyConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_slam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'realsense_ros_slam': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_slam/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f02ead1dd88aaa736f807c98890ab00c";
  }

  static const char* value(const ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf02ead1dd88aaa73ULL;
  static const uint64_t static_value2 = 0x6f807c98890ab00cULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_slam/TrackingAccuracy";
  }

  static const char* value(const ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
uint32 tracking_accuracy\n\
\n\
#tracking_accuracy types constants\n\
int32 TRACKING_ACCURACY_FAILED=0\n\
int32 TRACKING_ACCURACY_LOW=1\n\
int32 TRACKING_ACCURACY_MEDIUM=2\n\
int32 TRACKING_ACCURACY_HIGH=3\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracking_accuracy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackingAccuracy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_slam::TrackingAccuracy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracking_accuracy: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tracking_accuracy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_SLAM_MESSAGE_TRACKINGACCURACY_H
