# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_ros_person/EulerAnglesWithConfidence.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import realsense_ros_person.msg

class EulerAnglesWithConfidence(genpy.Message):
  _md5sum = "5e76354a4d10460adcef4d7d5dd74f1f"
  _type = "realsense_ros_person/EulerAnglesWithConfidence"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """EulerAngles angles
int32 confidence

================================================================================
MSG: realsense_ros_person/EulerAngles
float32 pitch
float32 roll
float32 yaw
"""
  __slots__ = ['angles','confidence']
  _slot_types = ['realsense_ros_person/EulerAngles','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angles,confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EulerAnglesWithConfidence, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.angles is None:
        self.angles = realsense_ros_person.msg.EulerAngles()
      if self.confidence is None:
        self.confidence = 0
    else:
      self.angles = realsense_ros_person.msg.EulerAngles()
      self.confidence = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fi().pack(_x.angles.pitch, _x.angles.roll, _x.angles.yaw, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.angles is None:
        self.angles = realsense_ros_person.msg.EulerAngles()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.angles.pitch, _x.angles.roll, _x.angles.yaw, _x.confidence,) = _get_struct_3fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fi().pack(_x.angles.pitch, _x.angles.roll, _x.angles.yaw, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.angles is None:
        self.angles = realsense_ros_person.msg.EulerAngles()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.angles.pitch, _x.angles.roll, _x.angles.yaw, _x.confidence,) = _get_struct_3fi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fi = None
def _get_struct_3fi():
    global _struct_3fi
    if _struct_3fi is None:
        _struct_3fi = struct.Struct("<3fi")
    return _struct_3fi
