# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_ros_person/SkeletonJoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class SkeletonJoint(genpy.Message):
  _md5sum = "dfca6d8f4a6c4e847fc126d5f1b7b05b"
  _type = "realsense_ros_person/SkeletonJoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 type
float32 confidence
geometry_msgs/Point location
geometry_msgs/Point32 realWorldCoordinates

#joint types constants
int32 JOINT_ANKLE_LEFT=0
int32 JOINT_ANKLE_RIGHT=1
int32 JOINT_ELBOW_LEFT=2
int32 JOINT_ELBOW_RIGHT=3
int32 JOINT_FOOT_LEFT=4
int32 JOINT_FOOT_RIGHT=5
int32 JOINT_HAND_LEFT=6
int32 JOINT_HAND_RIGHT=7
int32 JOINT_HAND_TIP_LEFT=8
int32 JOINT_HAND_TIP_RIGHT=9
int32 JOINT_HEAD=10
int32 JOINT_HIP_LEFT=11
int32 JOINT_HIP_RIGHT=12
int32 JOINT_KNEE_LEFT=13
int32 JOINT_KNEE_RIGHT=14
int32 JOINT_NECK=15
int32 JOINT_SHOULDER_LEFT=16
int32 JOINT_SHOULDER_RIGHT=17
int32 JOINT_SPINE_BASE=18
int32 JOINT_SPINE_MID=19
int32 JOINT_SPINE_SHOULDER=20
int32 JOINT_THUMB_LEFT=21
int32 JOINT_THUMB_RIGHT=22
int32 JOINT_WRIST_LEFT=23
int32 JOINT_WRIST_RIGHT=24
int32 JOINT_UNKNOWN=25

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  # Pseudo-constants
  JOINT_ANKLE_LEFT = 0
  JOINT_ANKLE_RIGHT = 1
  JOINT_ELBOW_LEFT = 2
  JOINT_ELBOW_RIGHT = 3
  JOINT_FOOT_LEFT = 4
  JOINT_FOOT_RIGHT = 5
  JOINT_HAND_LEFT = 6
  JOINT_HAND_RIGHT = 7
  JOINT_HAND_TIP_LEFT = 8
  JOINT_HAND_TIP_RIGHT = 9
  JOINT_HEAD = 10
  JOINT_HIP_LEFT = 11
  JOINT_HIP_RIGHT = 12
  JOINT_KNEE_LEFT = 13
  JOINT_KNEE_RIGHT = 14
  JOINT_NECK = 15
  JOINT_SHOULDER_LEFT = 16
  JOINT_SHOULDER_RIGHT = 17
  JOINT_SPINE_BASE = 18
  JOINT_SPINE_MID = 19
  JOINT_SPINE_SHOULDER = 20
  JOINT_THUMB_LEFT = 21
  JOINT_THUMB_RIGHT = 22
  JOINT_WRIST_LEFT = 23
  JOINT_WRIST_RIGHT = 24
  JOINT_UNKNOWN = 25

  __slots__ = ['type','confidence','location','realWorldCoordinates']
  _slot_types = ['int32','float32','geometry_msgs/Point','geometry_msgs/Point32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,confidence,location,realWorldCoordinates

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SkeletonJoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.confidence is None:
        self.confidence = 0.
      if self.location is None:
        self.location = geometry_msgs.msg.Point()
      if self.realWorldCoordinates is None:
        self.realWorldCoordinates = geometry_msgs.msg.Point32()
    else:
      self.type = 0
      self.confidence = 0.
      self.location = geometry_msgs.msg.Point()
      self.realWorldCoordinates = geometry_msgs.msg.Point32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_if3d3f().pack(_x.type, _x.confidence, _x.location.x, _x.location.y, _x.location.z, _x.realWorldCoordinates.x, _x.realWorldCoordinates.y, _x.realWorldCoordinates.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.location is None:
        self.location = geometry_msgs.msg.Point()
      if self.realWorldCoordinates is None:
        self.realWorldCoordinates = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.type, _x.confidence, _x.location.x, _x.location.y, _x.location.z, _x.realWorldCoordinates.x, _x.realWorldCoordinates.y, _x.realWorldCoordinates.z,) = _get_struct_if3d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_if3d3f().pack(_x.type, _x.confidence, _x.location.x, _x.location.y, _x.location.z, _x.realWorldCoordinates.x, _x.realWorldCoordinates.y, _x.realWorldCoordinates.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.location is None:
        self.location = geometry_msgs.msg.Point()
      if self.realWorldCoordinates is None:
        self.realWorldCoordinates = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.type, _x.confidence, _x.location.x, _x.location.y, _x.location.z, _x.realWorldCoordinates.x, _x.realWorldCoordinates.y, _x.realWorldCoordinates.z,) = _get_struct_if3d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_if3d3f = None
def _get_struct_if3d3f():
    global _struct_if3d3f
    if _struct_if3d3f is None:
        _struct_if3d3f = struct.Struct("<if3d3f")
    return _struct_if3d3f
