// Generated by gencpp from file az5/simple_vel.msg
// DO NOT EDIT!


#ifndef AZ5_MESSAGE_SIMPLE_VEL_H
#define AZ5_MESSAGE_SIMPLE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace az5
{
template <class ContainerAllocator>
struct simple_vel_
{
  typedef simple_vel_<ContainerAllocator> Type;

  simple_vel_()
    : x(0)
    , y(0)
    , theta(0)  {
    }
  simple_vel_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::az5::simple_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::az5::simple_vel_<ContainerAllocator> const> ConstPtr;

}; // struct simple_vel_

typedef ::az5::simple_vel_<std::allocator<void> > simple_vel;

typedef boost::shared_ptr< ::az5::simple_vel > simple_velPtr;
typedef boost::shared_ptr< ::az5::simple_vel const> simple_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::az5::simple_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::az5::simple_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace az5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'az5': ['/home/complubot/Documents/POLLOTRON/CODE/ros/pollotron/src/az5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::az5::simple_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::az5::simple_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::az5::simple_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::az5::simple_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::az5::simple_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::az5::simple_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::az5::simple_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bff1127cd10ca02349c9c72c72be56e";
  }

  static const char* value(const ::az5::simple_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bff1127cd10ca02ULL;
  static const uint64_t static_value2 = 0x349c9c72c72be56eULL;
};

template<class ContainerAllocator>
struct DataType< ::az5::simple_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "az5/simple_vel";
  }

  static const char* value(const ::az5::simple_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::az5::simple_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 theta\n\
";
  }

  static const char* value(const ::az5::simple_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::az5::simple_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::az5::simple_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::az5::simple_vel_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AZ5_MESSAGE_SIMPLE_VEL_H
