# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_ros_object/Location3D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Location3D(genpy.Message):
  _md5sum = "9d0d637baabd2a2edf3e785062238586"
  _type = "realsense_ros_object/Location3D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point32 coordinates
float32 horiz_margin
float32 vert_margin

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['coordinates','horiz_margin','vert_margin']
  _slot_types = ['geometry_msgs/Point32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       coordinates,horiz_margin,vert_margin

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Location3D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.coordinates is None:
        self.coordinates = geometry_msgs.msg.Point32()
      if self.horiz_margin is None:
        self.horiz_margin = 0.
      if self.vert_margin is None:
        self.vert_margin = 0.
    else:
      self.coordinates = geometry_msgs.msg.Point32()
      self.horiz_margin = 0.
      self.vert_margin = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.coordinates.x, _x.coordinates.y, _x.coordinates.z, _x.horiz_margin, _x.vert_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.coordinates is None:
        self.coordinates = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.coordinates.x, _x.coordinates.y, _x.coordinates.z, _x.horiz_margin, _x.vert_margin,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.coordinates.x, _x.coordinates.y, _x.coordinates.z, _x.horiz_margin, _x.vert_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.coordinates is None:
        self.coordinates = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.coordinates.x, _x.coordinates.y, _x.coordinates.z, _x.horiz_margin, _x.vert_margin,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
