# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_ros_object/ObjectsInBoxes.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import realsense_ros_object.msg
import geometry_msgs.msg
import std_msgs.msg

class ObjectsInBoxes(genpy.Message):
  _md5sum = "766265c76170a5de1a5179aa1e37cf42"
  _type = "realsense_ros_object/ObjectsInBoxes"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
ObjectInBox[] objects_vector
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: realsense_ros_object/ObjectInBox
Object object
Rect object_bbox
Location3D location

================================================================================
MSG: realsense_ros_object/Object
int32 label
string object_name
float32 probability

================================================================================
MSG: realsense_ros_object/Rect
int32 x
int32 y
int32 height
int32 width

================================================================================
MSG: realsense_ros_object/Location3D
geometry_msgs/Point32 coordinates
float32 horiz_margin
float32 vert_margin

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['header','objects_vector']
  _slot_types = ['std_msgs/Header','realsense_ros_object/ObjectInBox[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,objects_vector

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectsInBoxes, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects_vector is None:
        self.objects_vector = []
    else:
      self.header = std_msgs.msg.Header()
      self.objects_vector = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.objects_vector)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects_vector:
        _v1 = val1.object
        buff.write(_get_struct_i().pack(_v1.label))
        _x = _v1.object_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_f().pack(_v1.probability))
        _v2 = val1.object_bbox
        _x = _v2
        buff.write(_get_struct_4i().pack(_x.x, _x.y, _x.height, _x.width))
        _v3 = val1.location
        _v4 = _v3.coordinates
        _x = _v4
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _x = _v3
        buff.write(_get_struct_2f().pack(_x.horiz_margin, _x.vert_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects_vector is None:
        self.objects_vector = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects_vector = []
      for i in range(0, length):
        val1 = realsense_ros_object.msg.ObjectInBox()
        _v5 = val1.object
        start = end
        end += 4
        (_v5.label,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v5.object_name = str[start:end].decode('utf-8')
        else:
          _v5.object_name = str[start:end]
        start = end
        end += 4
        (_v5.probability,) = _get_struct_f().unpack(str[start:end])
        _v6 = val1.object_bbox
        _x = _v6
        start = end
        end += 16
        (_x.x, _x.y, _x.height, _x.width,) = _get_struct_4i().unpack(str[start:end])
        _v7 = val1.location
        _v8 = _v7.coordinates
        _x = _v8
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        _x = _v7
        start = end
        end += 8
        (_x.horiz_margin, _x.vert_margin,) = _get_struct_2f().unpack(str[start:end])
        self.objects_vector.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.objects_vector)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects_vector:
        _v9 = val1.object
        buff.write(_get_struct_i().pack(_v9.label))
        _x = _v9.object_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_f().pack(_v9.probability))
        _v10 = val1.object_bbox
        _x = _v10
        buff.write(_get_struct_4i().pack(_x.x, _x.y, _x.height, _x.width))
        _v11 = val1.location
        _v12 = _v11.coordinates
        _x = _v12
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
        _x = _v11
        buff.write(_get_struct_2f().pack(_x.horiz_margin, _x.vert_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.objects_vector is None:
        self.objects_vector = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects_vector = []
      for i in range(0, length):
        val1 = realsense_ros_object.msg.ObjectInBox()
        _v13 = val1.object
        start = end
        end += 4
        (_v13.label,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v13.object_name = str[start:end].decode('utf-8')
        else:
          _v13.object_name = str[start:end]
        start = end
        end += 4
        (_v13.probability,) = _get_struct_f().unpack(str[start:end])
        _v14 = val1.object_bbox
        _x = _v14
        start = end
        end += 16
        (_x.x, _x.y, _x.height, _x.width,) = _get_struct_4i().unpack(str[start:end])
        _v15 = val1.location
        _v16 = _v15.coordinates
        _x = _v16
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        _x = _v15
        start = end
        end += 8
        (_x.horiz_margin, _x.vert_margin,) = _get_struct_2f().unpack(str[start:end])
        self.objects_vector.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
