# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from realsense_ros_object/ObjectInBox.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import realsense_ros_object.msg
import geometry_msgs.msg

class ObjectInBox(genpy.Message):
  _md5sum = "506c556ef4808f18c8fda7a0b6d365a7"
  _type = "realsense_ros_object/ObjectInBox"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Object object
Rect object_bbox
Location3D location

================================================================================
MSG: realsense_ros_object/Object
int32 label
string object_name
float32 probability

================================================================================
MSG: realsense_ros_object/Rect
int32 x
int32 y
int32 height
int32 width

================================================================================
MSG: realsense_ros_object/Location3D
geometry_msgs/Point32 coordinates
float32 horiz_margin
float32 vert_margin

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['object','object_bbox','location']
  _slot_types = ['realsense_ros_object/Object','realsense_ros_object/Rect','realsense_ros_object/Location3D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object,object_bbox,location

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectInBox, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.object is None:
        self.object = realsense_ros_object.msg.Object()
      if self.object_bbox is None:
        self.object_bbox = realsense_ros_object.msg.Rect()
      if self.location is None:
        self.location = realsense_ros_object.msg.Location3D()
    else:
      self.object = realsense_ros_object.msg.Object()
      self.object_bbox = realsense_ros_object.msg.Rect()
      self.location = realsense_ros_object.msg.Location3D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_i().pack(self.object.label))
      _x = self.object.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f4i5f().pack(_x.object.probability, _x.object_bbox.x, _x.object_bbox.y, _x.object_bbox.height, _x.object_bbox.width, _x.location.coordinates.x, _x.location.coordinates.y, _x.location.coordinates.z, _x.location.horiz_margin, _x.location.vert_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.object is None:
        self.object = realsense_ros_object.msg.Object()
      if self.object_bbox is None:
        self.object_bbox = realsense_ros_object.msg.Rect()
      if self.location is None:
        self.location = realsense_ros_object.msg.Location3D()
      end = 0
      start = end
      end += 4
      (self.object.label,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object.object_name = str[start:end].decode('utf-8')
      else:
        self.object.object_name = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.object.probability, _x.object_bbox.x, _x.object_bbox.y, _x.object_bbox.height, _x.object_bbox.width, _x.location.coordinates.x, _x.location.coordinates.y, _x.location.coordinates.z, _x.location.horiz_margin, _x.location.vert_margin,) = _get_struct_f4i5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_i().pack(self.object.label))
      _x = self.object.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f4i5f().pack(_x.object.probability, _x.object_bbox.x, _x.object_bbox.y, _x.object_bbox.height, _x.object_bbox.width, _x.location.coordinates.x, _x.location.coordinates.y, _x.location.coordinates.z, _x.location.horiz_margin, _x.location.vert_margin))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.object is None:
        self.object = realsense_ros_object.msg.Object()
      if self.object_bbox is None:
        self.object_bbox = realsense_ros_object.msg.Rect()
      if self.location is None:
        self.location = realsense_ros_object.msg.Location3D()
      end = 0
      start = end
      end += 4
      (self.object.label,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object.object_name = str[start:end].decode('utf-8')
      else:
        self.object.object_name = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.object.probability, _x.object_bbox.x, _x.object_bbox.y, _x.object_bbox.height, _x.object_bbox.width, _x.location.coordinates.x, _x.location.coordinates.y, _x.location.coordinates.z, _x.location.horiz_margin, _x.location.vert_margin,) = _get_struct_f4i5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_f4i5f = None
def _get_struct_f4i5f():
    global _struct_f4i5f
    if _struct_f4i5f is None:
        _struct_f4i5f = struct.Struct("<f4i5f")
    return _struct_f4i5f
