(cl:defpackage realsense_ros_object-msg
  (:use )
  (:export
   "<FRAME>"
   "FRAME"
   "<GESTURES>"
   "GESTURES"
   "<LANDMARK>"
   "LANDMARK"
   "<LOCATION3D>"
   "LOCATION3D"
   "<OBJECT>"
   "OBJECT"
   "<OBJECTARRAY>"
   "OBJECTARRAY"
   "<OBJECTINBOX>"
   "OBJECTINBOX"
   "<OBJECTSINBOXES>"
   "OBJECTSINBOXES"
   "<POINTING>"
   "POINTING"
   "<RECT>"
   "RECT"
   "<TRACKEDOBJECT>"
   "TRACKEDOBJECT"
   "<TRACKEDOBJECTSARRAY>"
   "TRACKEDOBJECTSARRAY"
   "<UI>"
   "UI"
   "<USER>"
   "USER"
   "<USERINFO>"
   "USERINFO"
   "<CPU_GPU>"
   "CPU_GPU"
  ))

