---
RAMA: ELECTRONICA
PROYECTO: POLLOTRON
title: "Pasos prototipado"
output: 
  pdf_document:
    fig_caption: true
    number_sections: true
---

\tableofcontents

## Crear el modelo

* Para ellos hemos utilizado kicad *Se han incluido componentes de varias librerías*
* Utilizar meddias estandar para las dimensiones entre los tornillos y de los bordes de la placa

\newpage

## Imprimir el modelo

* Exportar el modelo a .pdf
* Comprobar como imprime la impresora, para saber la dirección en la que hay que poner la hoja
* NO se pueden usar las hojas amarillas directamente en la impresora porque patian!!!
* Utilizar la hoja de prueba para pegar un trozo de hoja amarilla sobre la silueta de las placas
* Imprimir el modelo sobre la cara brillante del papel
    * Utilizar 100% como escala
    * Poner la resolución al máximo
*  **Comprobar que las dimensiones son correctas!!!**

## Preaparar los materiales

* En caso de estar manchadas de tinta limpiar con acetona y dejar que se evapore
* Limpiar las placas con alcohol para quitarles el óxido
* Deben de estar limpias justo antes de comenzar pues se oxidan rápido
* Tener lista una bandeja con agua fría y una brocha

### Materiales para quemar el cobre

* PERCARBONATO **(40g)**
* ÁCIDO CLORHÍDRICO **(250ml)**
* Báscula y probeta para hacer las medidas
* Bandeja para realizar la reacción

## PLANCHAR LA IMPRESION SOBRE EL COBRE

* Poner la plancha al máximo de temperatura
* La placa debe estar entre paños para no quemar la mesa
* Primero calentar directamente el papel puesto encima de la placa 
* Cuando hayan pasado unos 5 min y no se pueda seguir calentando el papel directamente pues se quema comenzar a hacerlo sobre los trapos
* En total se debe estar entre 15 y 20 min calentando
* Finalmete hechar la placa en agua fría y dejar que el papel se despegue solo
* Se puede ayudar al papel con una brocha despúes de que lleve un rato ya en el agua

## Quemar el cobre

* Primero se hechar el clorhídrico
* Luego se mete dentro la placa
* Finalmete se hecha el percarbonato para activar la reacción
