// Generated by gencpp from file realsense_ros_object/Location3D.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_OBJECT_MESSAGE_LOCATION3D_H
#define REALSENSE_ROS_OBJECT_MESSAGE_LOCATION3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace realsense_ros_object
{
template <class ContainerAllocator>
struct Location3D_
{
  typedef Location3D_<ContainerAllocator> Type;

  Location3D_()
    : coordinates()
    , horiz_margin(0.0)
    , vert_margin(0.0)  {
    }
  Location3D_(const ContainerAllocator& _alloc)
    : coordinates(_alloc)
    , horiz_margin(0.0)
    , vert_margin(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _coordinates_type;
  _coordinates_type coordinates;

   typedef float _horiz_margin_type;
  _horiz_margin_type horiz_margin;

   typedef float _vert_margin_type;
  _vert_margin_type vert_margin;





  typedef boost::shared_ptr< ::realsense_ros_object::Location3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_object::Location3D_<ContainerAllocator> const> ConstPtr;

}; // struct Location3D_

typedef ::realsense_ros_object::Location3D_<std::allocator<void> > Location3D;

typedef boost::shared_ptr< ::realsense_ros_object::Location3D > Location3DPtr;
typedef boost::shared_ptr< ::realsense_ros_object::Location3D const> Location3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_object::Location3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_object::Location3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_object

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'realsense_ros_object': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_object/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_object::Location3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_object::Location3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_object::Location3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_object::Location3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_object::Location3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_object::Location3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_object::Location3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d0d637baabd2a2edf3e785062238586";
  }

  static const char* value(const ::realsense_ros_object::Location3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d0d637baabd2a2eULL;
  static const uint64_t static_value2 = 0xdf3e785062238586ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_object::Location3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_object/Location3D";
  }

  static const char* value(const ::realsense_ros_object::Location3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_object::Location3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32 coordinates\n\
float32 horiz_margin\n\
float32 vert_margin\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::realsense_ros_object::Location3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_object::Location3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coordinates);
      stream.next(m.horiz_margin);
      stream.next(m.vert_margin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Location3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_object::Location3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_object::Location3D_<ContainerAllocator>& v)
  {
    s << indent << "coordinates: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.coordinates);
    s << indent << "horiz_margin: ";
    Printer<float>::stream(s, indent + "  ", v.horiz_margin);
    s << indent << "vert_margin: ";
    Printer<float>::stream(s, indent + "  ", v.vert_margin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_OBJECT_MESSAGE_LOCATION3D_H
