// Generated by gencpp from file realsense_ros_object/TrackedObjectsArray.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_OBJECT_MESSAGE_TRACKEDOBJECTSARRAY_H
#define REALSENSE_ROS_OBJECT_MESSAGE_TRACKEDOBJECTSARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <realsense_ros_object/TrackedObject.h>

namespace realsense_ros_object
{
template <class ContainerAllocator>
struct TrackedObjectsArray_
{
  typedef TrackedObjectsArray_<ContainerAllocator> Type;

  TrackedObjectsArray_()
    : header()
    , tracked_objects_vector()  {
    }
  TrackedObjectsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracked_objects_vector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::realsense_ros_object::TrackedObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::realsense_ros_object::TrackedObject_<ContainerAllocator> >::other >  _tracked_objects_vector_type;
  _tracked_objects_vector_type tracked_objects_vector;





  typedef boost::shared_ptr< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObjectsArray_

typedef ::realsense_ros_object::TrackedObjectsArray_<std::allocator<void> > TrackedObjectsArray;

typedef boost::shared_ptr< ::realsense_ros_object::TrackedObjectsArray > TrackedObjectsArrayPtr;
typedef boost::shared_ptr< ::realsense_ros_object::TrackedObjectsArray const> TrackedObjectsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_object

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'realsense_ros_object': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_object/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eba302ff867767c2d7dce5a9b84a6ec3";
  }

  static const char* value(const ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeba302ff867767c2ULL;
  static const uint64_t static_value2 = 0xd7dce5a9b84a6ec3ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_object/TrackedObjectsArray";
  }

  static const char* value(const ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
TrackedObject[] tracked_objects_vector\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: realsense_ros_object/TrackedObject\n\
Rect bbox\n\
int32 id \n\
Location3D location\n\
\n\
================================================================================\n\
MSG: realsense_ros_object/Rect\n\
int32 x\n\
int32 y\n\
int32 height\n\
int32 width\n\
\n\
================================================================================\n\
MSG: realsense_ros_object/Location3D\n\
geometry_msgs/Point32 coordinates\n\
float32 horiz_margin\n\
float32 vert_margin\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracked_objects_vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObjectsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_object::TrackedObjectsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracked_objects_vector[]" << std::endl;
    for (size_t i = 0; i < v.tracked_objects_vector.size(); ++i)
    {
      s << indent << "  tracked_objects_vector[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::realsense_ros_object::TrackedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.tracked_objects_vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_OBJECT_MESSAGE_TRACKEDOBJECTSARRAY_H
