// Generated by gencpp from file realsense_ros_object/UI.msg
// DO NOT EDIT!


#ifndef REALSENSE_ROS_OBJECT_MESSAGE_UI_H
#define REALSENSE_ROS_OBJECT_MESSAGE_UI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realsense_ros_object
{
template <class ContainerAllocator>
struct UI_
{
  typedef UI_<ContainerAllocator> Type;

  UI_()
    : key(0)  {
    }
  UI_(const ContainerAllocator& _alloc)
    : key(0)  {
  (void)_alloc;
    }



   typedef int32_t _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::realsense_ros_object::UI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_ros_object::UI_<ContainerAllocator> const> ConstPtr;

}; // struct UI_

typedef ::realsense_ros_object::UI_<std::allocator<void> > UI;

typedef boost::shared_ptr< ::realsense_ros_object::UI > UIPtr;
typedef boost::shared_ptr< ::realsense_ros_object::UI const> UIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_ros_object::UI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_ros_object::UI_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace realsense_ros_object

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'realsense_ros_object': ['/home/complubot/Documents/POLLOTRON/CODE/ros/realsense_examples/src/realsense_samples_ros/realsense_ros_object/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_object::UI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_ros_object::UI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_object::UI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_ros_object::UI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_object::UI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_ros_object::UI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_ros_object::UI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5f7d6b16cb4e9d7a81b607f04247968";
  }

  static const char* value(const ::realsense_ros_object::UI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5f7d6b16cb4e9d7ULL;
  static const uint64_t static_value2 = 0xa81b607f04247968ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_ros_object::UI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_ros_object/UI";
  }

  static const char* value(const ::realsense_ros_object::UI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_ros_object::UI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 key\n\
";
  }

  static const char* value(const ::realsense_ros_object::UI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_ros_object::UI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_ros_object::UI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_ros_object::UI_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<int32_t>::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_ROS_OBJECT_MESSAGE_UI_H
